const assets = {
    asterisk: '/magenta-asterisk.svg',
    circle: '/magenta-circle.svg',
    circle2: '/magenta-circle2.svg',
    trap: '/green-trap.svg',
    logo: '/logo.svg',
    arrow: '/white-arrow.svg',
    arrow2: '/white-arrow2.svg',
    minus: '/minus.svg',
    yellowHex: '/yellow-hex.svg',
    hex: '/yellow-hex-full.svg',
    dots: '/dots.svg',
    arrowWhite: '/white-arrow-down.svg',
    isoIcon: '/iso.svg',
    cloud: '/magenta-cloud.svg',
    swiper1: '/thumb-01.jpg',
    swiper2: '/thumb-02.jpg',
    swiper3: '/thumb-03.jpg',
    swiper4: '/thumb-04.jpg',
    swiper5: '/thumb-05.jpg',
    swiper6: '/thumb-06.jpg',
    arrowBlack: '/right-arrow-black.svg',
    bearYellow: '/yellow-bear.svg',
    yellowArrow: '/yellow-arrows.svg',
    whiteArrow: '/white-arrows.svg',
    news1 : '/news-01.jpg',
    news2 : '/news-02.jpg',
    news3 : '/news-03.jpg',
    news4 : '/news-04.jpg',
    news5 : '/news-05.jpg',
    news6 : '/news-06.jpg',
    news7 : '/news-07.jpg',
    news8 : '/news-08.jpg',
    smile : '/white-smile.svg',
    bear: '/bear-misc.svg',
    instagram : '/instagram.svg',
    email : '/email.svg',
    globe : '/globe.svg',
    info : '/information.svg',
    wsp : '/whatsapp.svg',
  };
  
  export default assets;